name = "FishTank"
uuid = "b38b52d1-0eac-4161-8266-eab412337ac4"
authors = ["Jake W. Liu"]
version = "1.1.3"

[deps]
BeepBeep = "97dd0070-d6c0-43ac-b134-ca84cdbd343e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshGrid = "ebf956a0-ef5e-43be-9fb1-27952996e635"
PlotlyGeometries = "da4dd95e-df4f-4caf-ac06-cee3b0f5c2e6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
BeepBeep = "0.1"
Distributions = "0.25"
FFTW = "1.8"
MeshGrid = "1.0.2"
PlotlyGeometries = "1.1.0"
PlotlyJS = "0.18"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
